name: Lint

on:
  push:
    branches:
      - kickNV

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup `lua`
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: 5.4
          
      - name: Setup `luarocks`
        uses: leafo/gh-actions-luarocks@v4
      - name: Setup ‘luacheck’
        run: |
          luarocks install luacheck
          luarocks install lanes
      - name: Run ‘luacheck’ linter
        run: luacheck -j$(nproc) .
   
    
      
